apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: marosguran/ambulance-ufe
  newName: marosguran/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20260317.1411 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
