apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: mg-ambulance-ufe-content
spec:
  microFrontend: mg-ambulance-ufe
  element: mg-ambulance-wl-app
  attributes:
  - name: api-base
    value: /mg-api
  - name: ambulance-id
    value: bobulova
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?mg-ambulance-wl(/.*)?$"